# Generated by Django 2.2.2 on 2019-06-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
